[package]
name = "frank"
version = "0.1.0"
authors = ["Jack Kavanagh <jackkav@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-testify = "0.3.0"
rustfix = "0.5.1"
